"""adding restaurant customer relationship

Revision ID: 2f566caf0afb
Revises: 8fdb2ba1bc21
Create Date: 2023-09-01 23:27:45.944607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f566caf0afb'
down_revision: Union[str, None] = '8fdb2ba1bc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
