"""adding description to review table

Revision ID: ef5cbf05f0e4
Revises: b8eaa2064425
Create Date: 2023-09-02 03:45:50.735940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5cbf05f0e4'
down_revision: Union[str, None] = 'b8eaa2064425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
