"""adding association proxy on the customer and restaurant tables

Revision ID: 0d780efc2b7e
Revises: 2f566caf0afb
Create Date: 2023-09-02 02:07:24.135015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d780efc2b7e'
down_revision: Union[str, None] = '2f566caf0afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
