"""adding restaurant customer relationship

Revision ID: 8fdb2ba1bc21
Revises: f74740ddd4fe
Create Date: 2023-09-01 23:00:29.807646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdb2ba1bc21'
down_revision: Union[str, None] = 'f74740ddd4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
